### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by LaurentBerger** [opencv-infrastructure/opencv.org#39]
In this page https://opencv.org/ link to Users and Q&A forum g is dead :
https://answers.opencv.org/questions/

**Comment by spmallick** [comment]
We have fixed the issue, but I am not 100% sure it is the same link you have mentioned. Can you please check it and let us know if it is indeed fixed.

**Comment by mshabunin** [comment]
We've enabled HTTPS for answers.opencv.org, so the link should work now.
