### ISSUE TITLE
broken "donate" link

### ISSUE THREAD

**Issue by berak** [opencv-infrastructure/opencv.org#40]
from: https://answers.opencv.org/question/213315/paypal-always-gives-an-error/

"Donate" button on the main opencv.org page leads to an expired session

**Comment by mshabunin** [comment]
**cc** @spmallick

**Comment by mshabunin** [comment]
While the issue is being fixed you can use "Donate" button on old page (https://opencv-infrastructure.github.io/opencv.org/)

**Comment by spmallick** [comment]
Looks like this message got filtered in my account. This is now fixed. Thanks for bringing this to our attention.
