### ISSUE TITLE
fix google ranking of versions on docs.opencv.org

### ISSUE THREAD

**Issue by crackwitz** [opencv-infrastructure/opencv.org#42]
google keeps showing people results for 2.4 or random 3.x docs. that is immensely unhelpful.

it *should* show trunk/master and then 3.x latest as the first two results in all cases except when asked for a specific version, and maybe not even that.

a simple fix would be setting robots.txt to only index master/trunk and 3.4. a better way is probably using a sitemap. even better would be to know what to do so any search engine can improve its results.

doxygen appears to use hashes to generate doc page names. that may be suboptimal, but also a problem the doxygen people should be aware of. generally I think they'll know better how to SEO doxygen docs.

**Comment by mshabunin** [comment]
I've added `X-Robots-Tag` as describe [here](https://developers.google.com/search/reference/robots_meta_tag) to all directories except `/3.4` and `/master`. Let's wait for a week or two and see what happen.

**Comment by crackwitz** [comment]
doesn't seem to have fixed it... googling for "opencv imshow" still gives me a link to 2.4 docs (and "tutroals" also, which I've been trying to get off the internet).

I took a peek at the headers my browser is getting for https://docs.opencv.org/2.4/ and `X-Robots-Tag` is not among them. maybe the server doesn't send it for my User Agent.

I would suggest changing the "old school" [robots.txt](https://docs.opencv.org/robots.txt) at the served root. currently it only disallows indexing of compressed files.

![image](https://user-images.githubusercontent.com/7065108/92996848-f2cba100-f50e-11ea-95f8-0c1e356aa199.png)

**Comment by mshabunin** [comment]
@crackwitz , looks like we forgot to add `X-Robots-Tag` to the `/2.4` folder, thank you for report. Some search results have been fixed already. I think we will change the filter to exclude all documentation except nightly from indexing.

As for using `robots.txt`... [This guide from Google](https://support.google.com/webmasters/answer/6332384) explains that in order to remove existing pages from the index, they must: 
a) be allowed by `robots.txt`
b) return corresponding `X-Robots-Tag`

**Comment by kamalbuilds** [comment]
Hi is the issue fixed?

**Comment by crackwitz** [comment]
I'd say mostly. Google still seems to (sometimes) prefer `3.x` URLs over the other branches, but I think that's acceptable.

**Comment by mshabunin** [comment]
I've checked several requests and as @crackwitz wrote it mostly works as expected. Let's consider this issue fixed.
