### ISSUE TITLE
github & Build farm icons

### ISSUE THREAD

**Issue by sturkmen72** [opencv-infrastructure/opencv.org#44]
![image](https://user-images.githubusercontent.com/12151541/87660188-5764bc80-c767-11ea-8776-f1c8188cf49e.png) Build farm
![image](https://user-images.githubusercontent.com/12151541/87660254-706d6d80-c767-11ea-8d2e-c796507e7c5e.png) Github

are these icons correct?

**Comment by mshabunin** [comment]
Looks like these icons should be swapped.
**cc** @spmallick

**Comment by vikasgupta-github** [comment]
This has been fixed. Thanks!
