### ISSUE TITLE
docs.opencv.org talks about "WebFaction"

### ISSUE THREAD

**Issue by crackwitz** [opencv-infrastructure/opencv.org#47]
this "site" also delivers an invalid certificate.

right now, reproducible by going to https://docs.opencv.org/

**Comment by alalek** [comment]
issue in opencv repo: https://github.com/opencv/opencv/issues/20426

pullrequest.opencv.org is down too.

**Comment by mshabunin** [comment]
Issue have been fixed, thanks for reporting.
