### ISSUE TITLE
OpenCV-Python Tutorials->Image Processing in OpenCV->Smoothing Images:  BGR/RGB mismatch in code example

### ISSUE THREAD

**Issue by ZvikaZ** [opencv-infrastructure/opencv.org#50]
The first code example at https://docs.opencv.org/4.5.4/d4/d13/tutorial_py_filtering.html loads an image file with `cv.imread`, and then displays it with `plt.imshow`. However, since OpenCV uses BGR ordering, while Matplotlib uses RGB ordering, the image is showed with wrong colors (as discussed, e.g., at https://stackoverflow.com/a/50963621/1543290)

This can be easily solved by modifying:
```python
plt.subplot(121),plt.imshow(img),plt.title('Original')
...
plt.subplot(122),plt.imshow(dst),plt.title('Averaging')
```
To:
```python
plt.subplot(121),plt.imshow(cv.cvtColor(img, cv.COLOR_BGR2RGB)),plt.title('Original')
...
plt.subplot(122),plt.imshow(cv.cvtColor(dst, cv.COLOR_BGR2RGB)),plt.title('Averaging')
```

It's also worth mentioning as a side note near that code - the problem and the solution.

**Comment by alalek** [comment]
Hi, Thank you for the report!

Documentation and tutorials content is part of https://github.com/opencv/opencv repository.
This repository is about **infrastructure** issues.

Mentioned code is stored in this file: https://github.com/opencv/opencv/blob/4.x/doc/py_tutorials/py_imgproc/py_filtering/py_filtering.markdown

Feel free to prepare PR with changes or re-open issue in the right repository.

Original OpenCV logo has red figure on the top: https://github.com/opencv/opencv/blob/4.x/doc/opencv-logo.png
Please note that linked image is corresponds to the code (with RGB/BGR swap).
So with updated code we need to update the tutorial image too.

**Comment by ZvikaZ** [comment]
Thanks for the detailed reply.
