### ISSUE TITLE
The description about license of OpenCV is old

### ISSUE THREAD

**Issue by atinfinity** [opencv-infrastructure/opencv.org#51]
In <https://opencv.org/>, there is the following description about license of OpenCV.

> OpenCV is open source and released under the BSD 3-Clause License.

![Screenshot from 2022-08-01 22-45-11](https://user-images.githubusercontent.com/2630323/182161802-95b9df22-35ee-4510-8c06-4fa5256eb12f.png)

I think that this description is old.  
<https://opencv.org/license/>

**Comment by mshabunin** [comment]
Fixed, thank you!
