### ISSUE TITLE
forum.opencv.org DNS cannot be resolved

### ISSUE THREAD

**Issue by crackwitz** [opencv-infrastructure/opencv.org#54]
I tried this from different internet uplinks with different DNS servers. DNS resolution fails with SERVFAIL

This had not been the case ~12 hours ago. Then I could access the forum just fine.

*Down for Everyone or Just Me* [agrees with me](https://downforeveryoneorjustme.com/forum.opencv.org).

**Comment by vikasgupta-github** [comment]
Thanks for the post @crackwitz. There was an issue with cloudflare nameservers. It has been fixed now. Please report if you find anything failing.
